name: new_app_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Hive for local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Add flutter_rating_bar package
  flutter_rating_bar: ^4.0.1
  
  # Add shared_preferences package
  shared_preferences: ^2.2.2
  
  # Add url_launcher package (optional)
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true